---
- hosts: vms
  name: Using Command Module
  tasks:
    - name: gcloud version
      command: gcloud version
    - name: create a file
      file:
        name: file.txt
        state: touch
    - name: test (get)
      command: gcloud storage cp gs://ci-cd-oss-gcp-i-startup-script/startup-script.sh .
    - name: list objects
      command: gcloud storage ls
    - name: test (write/create)
      command: gcloud storage cp file.txt gs://ci-cd-oss-gcp-i-startup-script/
