---
- hosts: localhost
  become: true
  tasks:
    - name: Using command
      command: touch command.txt
---
- hosts: localhost
  tasks:
    - name: Create a file
      command: touch file.txt  
    - name: Create a directory
      command: mkdir file  