---
- hosts: vms
  name: Using Command Module
  tasks:
    - name: gcloud version
      command: gcloud version
    - name: create a file
      file:
        name: file.txt
        state: touch
    - name: copy data to cloud storage
      command: gcloud storage cp file.txt gs://ci-cd-oss-gcp-i-startup-script
