---
- hosts: vms
  name: Using Command Module
  tasks:
    - name: Create a file
      command: touch command.txt
    - name: Create a directory
      command: mkdir file  
    - name: Remove a file
      command: rm command.txt
    - name: Remove a directory
      command: rmdir file  